### ISSUE TITLE
can't build app

### ISSUE THREAD

**Issue by NaiveInvestigator** [martinellimarco/scream-android#1]
I get this error everytime i try to run `./gradlew build`
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Could not initialize class com.sun.xml.bind.v2.runtime.reflect.opt.Injector

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

```

Edit: Not so sure how to fix this, could we have a build on the release?

**Comment by martinellimarco** [comment]
Thank you for reporting this. It has been a while since I worked on this proof of concept.

I've upgraded the project all around and it is now building properly on my machine and opening on my phone.

I couldn't test it as I don't have access to a machine with scream right now but let me know if it doesn't work, I can fix it next week.

**Comment by NaiveInvestigator** [comment]
TYSM!!!! will try to build and report back!
